name: Waka Readme

on:
  schedule:
    - cron: "0 0 * * *" # Updates daily at midnight UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_COMMIT: "True"
          SHOW_TIMEZONE: "True"
          SHOW_LANGUAGE: "True"
          SHOW_EDITORS: "True"
          SHOW_OS: "True"
          SHOW_PROJECTS: "False"
          SHOW_LOC_CHART: "False"
